pipeline:
  name: varaci
  identifier: varaci
  projectIdentifier: IVAN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdude
        repoName: main
        build: <+input>
  stages:
    - stage:
        name: CIstage
        identifier: CIstage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "welcome to harness
